
-- Create user_state table
create table user_state (
  user_id uuid references auth.users not null primary key,
  profile jsonb,
  current_plan jsonb,
  shopping_list jsonb,
  last_notification bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create body_logs table
create table body_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date bigint not null,
  weight numeric,
  neck numeric,
  biceps numeric,
  chest numeric,
  waist numeric,
  hips numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create saved_plans table
create table saved_plans (
  id text primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at bigint not null,
  plan_data jsonb,
  user_profile jsonb,
  shopping_list jsonb
);

-- Enable Row Level Security (RLS)
alter table user_state enable row level security;
alter table body_logs enable row level security;
alter table saved_plans enable row level security;

-- Create policies
-- user_state policies
create policy "Users can view their own state" on user_state
  for select using (auth.uid() = user_id);

create policy "Users can insert their own state" on user_state
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own state" on user_state
  for update using (auth.uid() = user_id);

-- body_logs policies
create policy "Users can view their own logs" on body_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own logs" on body_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own logs" on body_logs
  for delete using (auth.uid() = user_id);

-- saved_plans policies
create policy "Users can view their own saved plans" on saved_plans
  for select using (auth.uid() = user_id);

create policy "Users can insert their own saved plans" on saved_plans
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own saved plans" on saved_plans
  for delete using (auth.uid() = user_id);
